alias hej='echo "Hej!" > hej.txt'
alias brc='vim ~/.bashrc; source ~/.bashrc'
alias ba='vim ~/.bash_aliases;source ~/.bash_aliases'
alias ll='ls -l'
alias l='git log --pretty=oneline|tig'
alias d='git diff|tig'
alias c='git commit'
alias p='git push'
alias po='git push origin'
alias pom='git push origin master'
alias b='git branch'
alias sublime='/home/samuel/opt/sublime/sublime_text'
galaxy_uppmax() {
    ssh -L 8181:localhost:34598 kalkyl.uppmax.uu.se 'ssh -t -t -L 34598:localhost:8080 $1 "sh /home/samuel/opt/galaxy/run.sh"'
}
alias switchjava='sudo update-alternatives --config java'
